name: safebuddy
description: A personal safety app with crime hotspot mapping.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_map: ^6.1.0
  gif: ^2.3.0
  flutter_dotenv: ^6.0.0
  latlong2: ^0.9.0
  flutter_local_notifications: ^17.0.0
  geolocator: ^11.0.0
  permission_handler: ^11.0.0
  window_manager: ^0.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  file_picker: ^6.0.0
  intl: ^0.18.1
  lottie: ^3.1.3
  # dart_serial_port: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/image/
    - assets/hotzones/